### PR TITLE
Update PSVUtils.js

### PR DESCRIPTION
**Pull request by marcin1337**
More universal way to detect if webgl is supported ( IE Edge )

### CODE REVIEW

**Comment by mistic100** [comment]
Please respect the codestyle (run `grunt test` )

And 
```js
if (PSVUtils.getWebGLCtx() != undefined)
                return true;
          else
               return false;
```
should be simplified to
```js
return PSVUtils.getWebGLCtx() !== undefined;
```

I also don't like the hardcoded lenght in `for (var i = 0; i < 4; i++) {`
You can use `names.forEach`

**Comment by mistic100** [comment]
Actually Array.some is a beter choice than Array.forEach

**Comment by marcin1337** [comment]
fixed the code style problems.

**Comment by mistic100** [comment]
The "context" variable will still point to a context object if it has no "getParameter" variable.

A correct usage is
```js
if (names.some(function(name) {
  try {
    context = canvas.getContext(name);
    return (context && typeof context.getParameter == 'function');
  } catch (e) {
    return false;
  }
})) {
  return context;
}
else {
  return undefined;
}
```

Wouldn't be a good idea to add "webgl2" and "experimental-webgl2" ?
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext

**Comment by marcin1337** [comment]
thanks for the pointers and your patience ( it is my first try at contributing to open source )

**Pull request closed without merging**
