### PR TITLE
Gallery Component click event handler offset increaset to allow mobile click

### PR DESCRIPTION
**Pull request by Elius94**
**Merge request checklist**

-   [x] All lints and tests pass. If needed, new unit tests were added.
-   [x] If needed, the [documentation](https://github.com/mistic100/Photo-Sphere-Viewer/tree/main/docs) has been updated.

### CODE REVIEW

**Comment by Elius94** [comment]
Ok, I'm gonna check

**Comment by Elius94** [comment]
Hey Damien, 

```ts
handleEvent(e: Event) {
        const clickOffset = window.innerWidth <= this.state.breakpoint ? 1000 : 10;
        switch (e.type) {
            case 'wheel': {
                if (window.innerWidth > this.state.breakpoint) {
                    const evt = e as WheelEvent;
                    const scrollAmount = this.plugin.config.thumbnailSize.width + this.state.itemMargin ?? 0;
                    this.items.scrollLeft += (evt.deltaY / Math.abs(evt.deltaY)) * scrollAmount;
                    e.preventDefault();
                }
                break;
            }

            case 'mousedown':
                this.state.mousedown = true;
                if (window.innerWidth > this.state.breakpoint) {
                    this.state.initMouse = (e as MouseEvent).clientX;
                } else {
                    this.state.initMouse = (e as MouseEvent).clientY;
                }
                this.state.mouse = this.state.initMouse;
                break;

            case 'mousemove':
                if (this.state.mousedown) {
                    if (window.innerWidth > this.state.breakpoint) {
                        const delta = this.state.mouse - (e as MouseEvent).clientX;
                        this.items.scrollLeft += delta;
                        this.state.mouse = (e as MouseEvent).clientX;
                    } else {
                        const delta = this.state.mouse - (e as MouseEvent).clientY;
                        this.items.scrollTop += delta;
                        this.state.mouse = (e as MouseEvent).clientY;
                    }
                }
                break;

            case 'mouseup':
                this.state.mousedown = false;
                this.state.mouse = null;
                e.preventDefault();
                break;

            case 'click':
                // prevent click on drag
                if (Math.abs(this.state.initMouse - (e as MouseEvent).clientX) < clickOffset) {
                    const item = utils.getClosest(e.target as HTMLElement, `[data-${GALLERY_ITEM_DATA_KEY}]`);
                    if (item) {
                        this.plugin.__click(item.dataset[GALLERY_ITEM_DATA]);
                    }
                }
                break;
        }
    }
```

Check this: simply adding a condition to change value of the click offset, now it's possible to click with mous, drag with mouse and also the same on smartphone touchscreens.

Let me know if you can test :)

**Comment by mistic100** [comment]
It was not a problem of offset, only of which coordinates is used 

```ts
const currentMouse = isAboveBreakpoint ? (e as MouseEvent).clientX : (e as MouseEvent).clientY;
if (Math.abs(this.state.initMouse - currentMouse) < 10) {
```

previously it always used "clientX"

**Comment by Elius94** [comment]
Super!! Here's what it was! Great :)it also explains why only the first line worked

**Comment by Elius94** [comment]
Super!! Here's what it was! Great :)it also explains why only the first line worked

**Pull request closed without merging**
