### PR TITLE
Created a fallback for IE 8/9/Edge Windows phone faulty background-position 

### PR DESCRIPTION
**Pull request by marcin1337**
The problem is that IE doesn't convert like in Chrome background-position of "bottom center" to percentages

**CHROME**

chrome

**IE EDGE**

ie

this results in the program hanging and a black screen

before

after giving fallback values it works
iefix

### CODE REVIEW

**Comment by mistic100** [comment]
When using merge request you must create a new branch from the original repository, not work on master. Because you end up in situations like this : you have 4 commits out of 5 that are totally irrelevant to the change you want. (I'm partly responsible for this because i manually merged your previous merge request, but it would not happened if you didn't work on your master branch).

Steps to clean up your repository (MAKE A COPY OF YOUR LOCAL REPO) :
1. create a branch on the relevant commit
```bash
$ git branch temp 107e5d7
```
2. Add my repo as remote
```bash
$ git remote add mistic100 git@github.com:mistic100/Photo-Sphere-Viewer.git
$ git fetch mistic100
``` 
3. reset your master to my master
```bash
$ git reset --hard mistic100/master
$ git push --force -u origin master
```
4. create a new branch
```bash
$ git checkout -b ie-fallback
```
5. retrieve your commit and delete temp branch
```bash
$ git cherry-pick 107e5d7
$ git branch -D temp
```
6. push the new branch
```bash
$ git push -u origin ie-fallback
```

7. close this merge request and create a new one for the new branch

---------------

If you have other changes to propose, start to update your master :
```bash
$ git checkout master 
$ git pull mistic100 master
```

and then create new branch before starting your changes.

**Comment by mistic100** [comment]
Now for the fallback specifically, I don't like to not be able to position the marker as the user want, it should work at least on IE11 and Edge.

I'll see if i find a suitable solution.

**Comment by mistic100** [comment]
More important : your merge request is empty, I discarded all your changes when manually merging from my branch

**Comment by marcin1337** [comment]
Thanks for the tips! :+1: 

as for the IE issue, I was thinking of creating a switch case with all of the css background-position values 


switch(pos){
case 'top left':
return '0% 0%';
case  'left top'
return '0% 0%';
case 'top right':
return '100% 0%';
...}

but this might be too hacky

**Comment by mistic100** [comment]
The `parsePosition`  could be rewritten with a manual parser, it's not that hard but I didn't do it because it was easier to rely on the browser parser.

Possible implementattion :
 - if the position contains a key word (left, right, top, bottom, center) find if the X position is the first or second token
 - replaces keywords by percentage values
 - parse percentage values

I'll do it, please open a issue :-)

**Pull request closed without merging**
