### PR TITLE
Update Viewer.ts for extends class and custom constructor method

### PR DESCRIPTION
**Pull request by Buminta**
**Merge request checklist**

-   [ ] All lints and tests pass. If needed, new unit tests were added.
-   [ ] If needed, the [documentation](https://github.com/mistic100/Photo-Sphere-Viewer/tree/main/docs) has been updated.

### CODE REVIEW

**Comment by mistic100** [comment]
What is the point of that ? You can already extends the class, and your custom constructor code will be called at exactly the same time.

```ts
class MyViewer extends Viewer {

    constructor(config) {
        super(config);

        // your code
    }

}
```

**Comment by Buminta** [comment]
@mistic100 inside constructor of Viewer has process and init plugins. It's will impact with plugins when plugin use get custom config of MyViewer class.

**Comment by mistic100** [comment]
```ts
class MyViewer extends Viewer {

    constructor(config) {
        super(this.alterConfig(config));
    }

    private alterConfig(config)  {
      .............
      return config;
    }

}
```

**Comment by Buminta** [comment]
> ```ts
> class MyViewer extends Viewer {
> 
>     constructor(config) {
>         super(this.alterConfig(config));
>     }
> 
>     private alterConfig(config)  {
>       .............
>       return config;
>     }
> 
> }
> ```

Nope! I wanna add more field for ViewerConfig.
Example:

```
export type PhotoConfig = ViewerConfig & {
  onChangePosition?: (position: any) => void;
}
```

**Comment by mistic100** [comment]
I don't see the problem.

Anyway I will not merge this PR, I do not agree with the design, I want to make sure the instance is initialized correctly by my specification or it will lead to unexpected errors.

**Pull request closed without merging**
