### PR TITLE
Make AMD setup compatible with case sensitive filesystems

### LINKED ISSUE #130: issue using this library
I wanted to use Photo Sphere Viewer in my project. So I ran

`npm i photo-sphere-viewer`
It appears to have downloaded the modules.

Then inside my project I did:

`import PhotoSphereViewer from 'photo-sphere-viewer/dist/photo-sphere-viewer';`
But I get error:

> Failed to compile.
> 
> Error in ./~/photo-sphere-viewer/dist/photo-sphere-viewer.js
> Module not found: 'D.js' in /home/ghy/WebstormProjects/mia-map/node_modules/photo-sphere-viewer/dist
> 
>  @ ./~/photo-sphere-viewer/dist/photo-sphere-viewer.js 9:4-55

Can anyone help me spot what is wrong?

PS. I think following line is causing issue (inside photo-sphere-viewer.js):

  ```
if (typeof define === 'function' && define.amd) {
    define(['three', 'D.js', 'uevent', 'doT'], factory);
  }
```
but I am even surprised why it enters inside this if as I didn't know I had require.js installed.

PPS. I have a react application created by create-react-app

### PR DESCRIPTION
**Pull request by gausie**
**Merge request checklist**

- [x] I read the [guidelines for contributing](https://github.com/mistic100/Photo-Sphere-Viewer/blob/master/.github/CONTRIBUTING.md)
- [x] I created my branch from `dev` and I am issuing the PR to `dev`
- [x] Unit tests are OK

This fixes #130

### CODE REVIEW

**Comment by mistic100** [comment]
@gausie you don't want to fix it ? just tell me

**Comment by gausie** [comment]
@mistic100 the CI is broken, test pass fine

**Comment by mistic100** [comment]
I am not talking about the ci but the change I requested.

**Comment by mistic100** [comment]
Rebase on my dev branch to fix the ci

**Comment by gausie** [comment]
What change have you requested, sorry?

**Comment by mistic100** [comment]
Don't you see the yellow block ?
> I think it should be dot/doT and same for the CommonJS loader. (the main file of dot requires fs)

**Pull request merged**
